# Generated by Django 4.0.1 on 2022-01-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=300)),
                ('sku', models.CharField(max_length=8)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
